<script>

</script>

<style>
.github {
        position: absolute;
        top: 80%;
        left:42.5%;
    }
    .linkedin{
        position: absolute;
        top: 80%;
        left:47.5%;
    }
    .gmail{
        position: absolute;
        top: 80%;
        left:52.5%;
    }
    .spotify{
        position: absolute;
        top: 80%;
        left:57.5%;
    }
</style>
<a href="https://github.com/AlphaLaser" target=”_blank”>
<span class="github">
    
    
        <img src="../images/github.png" width="40px" alt="github">
    

</span>
</a>
<a href = "https://linkedin.com/in/aditmagotra" target=”_blank”>
    <span class="linkedin">
        <img src="../images/linkedin.png" width="40px" alt="boy">
    </span>
</a>
<a href="mailto:aditmagotra@gmail.com">
    <span class="gmail">
        <img src="../images/gmail.png" width="40px" alt="boy">
    </span>
</a>

<a href="https://open.spotify.com/user/j280eb9ugb4m4gkdnbv7scayk?si=cc60de564b9b4178" target=”_blank”>
    <span class="spotify">
        <img src="../images/spotify.png" width="40px" alt="boy">
    </span>
</a>